import { Book } from "./types";

export const INITIAL_BOOKS: Book[] = [
  // Programming
  {
    id: "prog_1",
    title: "Effective Java",
    author: "Joshua Bloch",
    category: "Programming",
    description: "The definitive guide to Java platform best practices. It provides deep insights into the design of Java and contains expert advice on writing clear, robust, and performant code.",
    coverColor: "from-blue-700 to-indigo-900",
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80",
    ratingCount: 154,
    averageRating: 4.8,
    publishYear: 2018,
    pages: 412,
    tags: ["Java", "Best Practices", "Software Engineering", "Tech"]
  },
  {
    id: "prog_2",
    title: "Introduction to Algorithms",
    author: "Cormen, Leiserson, Rivest, Stein",
    category: "Programming",
    description: "The standard textbook for algorithm design and analysis. Covers a broad spectrum of algorithms in depth, yet makes their design and analysis accessible to all levels of readers.",
    coverColor: "from-slate-700 to-slate-950",
    coverImage: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=300&q=80",
    ratingCount: 98,
    averageRating: 4.7,
    publishYear: 2009,
    pages: 1292,
    tags: ["Algorithms", "Data Structures", "Computer Science", "Theory"]
  },
  {
    id: "prog_3",
    title: "Clean Code",
    author: "Robert C. Martin",
    category: "Programming",
    description: "A handbook of agile software craftsmanship. Teaches you how to write professional code that is clean, readable, testable, and highly maintainable.",
    coverColor: "from-emerald-700 to-teal-900",
    coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=300&q=80",
    ratingCount: 190,
    averageRating: 4.9,
    publishYear: 2008,
    pages: 464,
    tags: ["Clean Code", "Design Patterns", "Agile", "Refactoring"]
  },
  {
    id: "prog_4",
    title: "Head First Design Patterns",
    author: "Eric Freeman, Elisabeth Robson",
    category: "Programming",
    description: "A brain-friendly guide to design patterns. Learn how to write reusable, flexible, and elegant object-oriented code using proven designs.",
    coverColor: "from-sky-500 to-indigo-700",
    coverImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=300&q=80",
    ratingCount: 75,
    averageRating: 4.6,
    publishYear: 2004,
    pages: 694,
    tags: ["Design Patterns", "OOP", "Java", "Architecture"]
  },

  // Novel
  {
    id: "novel_1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Novel",
    description: "The classic novel set in the Jazz Age on Long Island, exploring themes of wealth, ambition, love, and the disillusionment of the American Dream.",
    coverColor: "from-amber-600 to-amber-900",
    coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80",
    ratingCount: 120,
    averageRating: 4.4,
    publishYear: 1925,
    pages: 180,
    tags: ["Classic", "Literature", "Fiction", "Jazz Age"]
  },
  {
    id: "novel_2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Novel",
    description: "A powerful story of race, justice, and childhood innocence in the American South, seen through the eyes of young Scout Finch.",
    coverColor: "from-rose-700 to-rose-950",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80",
    ratingCount: 145,
    averageRating: 4.9,
    publishYear: 1960,
    pages: 281,
    tags: ["Justice", "Classic", "Coming of Age", "Drama"]
  },
  {
    id: "novel_3",
    title: "1984",
    author: "George Orwell",
    category: "Novel",
    description: "A dystopian masterpiece exploring the chilling consequences of totalitarianism, surveillance, state control, and the manipulation of truth.",
    coverColor: "from-red-800 to-neutral-900",
    coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=300&q=80",
    ratingCount: 210,
    averageRating: 4.8,
    publishYear: 1949,
    pages: 328,
    tags: ["Dystopian", "Politics", "Surveillance", "Sci-Fi"]
  },
  {
    id: "novel_4",
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Novel",
    description: "An inspiring mystical fable about Santiago, an Andalusian shepherd boy who travels in search of worldly treasures, discovering the wisdom of listening to his heart.",
    coverColor: "from-yellow-600 to-amber-800",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80",
    ratingCount: 180,
    averageRating: 4.5,
    publishYear: 1988,
    pages: 163,
    tags: ["Philosophy", "Adventure", "Inspirational", "Quest"]
  },

  // History
  {
    id: "hist_1",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "History",
    description: "A sweeping narrative of human history, from the emergence of Homo sapiens in the Stone Age to the technological revolutions of the 21st century.",
    coverColor: "from-amber-700 to-stone-800",
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=300&q=80",
    ratingCount: 220,
    averageRating: 4.7,
    publishYear: 2011,
    pages: 443,
    tags: ["Humanity", "Evolution", "Anthropology", "Sociology"]
  },
  {
    id: "hist_2",
    title: "The Guns of August",
    author: "Barbara W. Tuchman",
    category: "History",
    description: "A Pulitzer Prize-winning classic history of the diplomatic crises and military maneuvers that led to the outbreak of World War I in the summer of 1914.",
    coverColor: "from-red-900 to-stone-900",
    coverImage: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=300&q=80",
    ratingCount: 40,
    averageRating: 4.5,
    publishYear: 1962,
    pages: 511,
    tags: ["WWI", "Military", "Diplomacy", "Europe"]
  },
  {
    id: "hist_3",
    title: "Alexander Hamilton",
    author: "Ron Chernow",
    category: "History",
    description: "The definitive biography of the brilliant, hot-tempered founding father who shaped the financial, political, and constitutional foundations of the United States.",
    coverColor: "from-amber-800 to-yellow-950",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=300&q=80",
    ratingCount: 65,
    averageRating: 4.8,
    publishYear: 2004,
    pages: 818,
    tags: ["Biography", "American History", "Politics", "Revolution"]
  },
  {
    id: "hist_4",
    title: "The Silk Roads: A New History of the World",
    author: "Peter Frankopan",
    category: "History",
    description: "An eye-opening trade and cultural exploration of world history, shifting the focus away from Europe towards the critical pathways connecting East and West.",
    coverColor: "from-indigo-900 to-yellow-700",
    coverImage: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=300&q=80",
    ratingCount: 52,
    averageRating: 4.6,
    publishYear: 2015,
    pages: 656,
    tags: ["Trade", "Asia", "Geopolitics", "Culture"]
  },

  // Science
  {
    id: "sci_1",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    category: "Science",
    description: "A landmark popular science book about cosmology, space, time, black holes, the Big Bang, and the general laws governing the universe.",
    coverColor: "from-indigo-950 to-purple-900",
    coverImage: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=300&q=80",
    ratingCount: 115,
    averageRating: 4.7,
    publishYear: 1988,
    pages: 212,
    tags: ["Cosmology", "Physics", "Universe", "Space"]
  },
  {
    id: "sci_2",
    title: "Cosmos",
    author: "Carl Sagan",
    category: "Science",
    description: "A magnificent exploration of the universe, science, and the human search for our place in the vast cosmic ocean, written with poetic elegance.",
    coverColor: "from-violet-800 to-indigo-950",
    coverImage: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=300&q=80",
    ratingCount: 95,
    averageRating: 4.9,
    publishYear: 1980,
    pages: 365,
    tags: ["Cosmos", "Philosophy", "Space Exploration", "Science"]
  },
  {
    id: "sci_3",
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    category: "Science",
    description: "A revolutionary book that reshaped our understanding of evolutionary biology by framing evolution around the survival and replication of genes.",
    coverColor: "from-green-800 to-emerald-950",
    coverImage: "https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?auto=format&fit=crop&w=300&q=80",
    ratingCount: 80,
    averageRating: 4.4,
    publishYear: 1976,
    pages: 360,
    tags: ["Biology", "Genetics", "Evolution", "Behavior"]
  }
];
